[server]
  name = "ssr-sub-hub"
  addr = ":1314" # 自定义端口
[server.logger]
  level = "debug" # 设置输出日志过滤等级

[redis]
  enable = false
  host = "localhost"
  port = "6379"
  password = ""
  db = 0
  expiration = 1200 # redis过期时间，单位为s

# 以下的配置可以热更新，更改后不需要重启
# 不同用户的配置文件通过用户名作为区分，见/user下的文件
# 由于viper读取用户个人配置文件不区分大小写
# 因此用户名不区分大小写时不能重复
# 例如：JabinGP jabingp不能共存
[[user]]
  username = "jabingp" # 配置用户名，登陆时区分大小写
  password = "jabingp" # 配置用户的密钥，区分大小写

[[user]]
  username = "sora"
  password = "sora"

[[user]]
  username = "mike7777777"
  password = "mike7777777"
